# Generated by Django 5.1.2 on 2024-11-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_cat_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(default='', upload_to='main_app/static/uploads/'),
        ),
    ]
